spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mapgis
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: Zz88921288
    data:
        redis:
            database: 1
            host: 127.0.0.1
            port: 6379
            password: Zz88921288
            timeout: 10s

logging:
    file:
        path: D:/App/logs
    level:
        root: info

mybatis-flex:
    mapper-locations: classpath:mapper/**/*Mapper.xml
    global-config:
        key-config:
            key-type: Generator
            value: snowFlakeId