server:
    port: 8000
    servlet:
        context-path: /mapgis
spring:
    application:
        name: mapgis
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: 300MB
            max-request-size: 500MB